# -*- coding: utf-8 -*-
"""0320.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w7Sdd7tlbDw4Kavsd_mgQUVKYL3tz64t
"""

# 서강대 2022 코딩 왜 백준은 틀렸다 하지? 이해가 안 되네
# 도움 받은 사이트 (알고리즘을 잘 모르겠어서 따라했고 내 식대로 문제를 풀어나감)
# https://gumgood.github.io/spc-2022-master-solution

# 평년, 윤년 구분 (2차원 배열)
leapOrCommon = [
    [0, 31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31],
    [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
]

# if 조건문 1줄로 쓰는 거 (https://noel-embedded.tistory.com/907) 
def solve():
  def check(y, m, d):
    return (y, m, d) >= (Y, M, D) if 1 <= m <= 12 and 1 <= d <= leapOrCommon[1 if(y%4) else 0][m] else -1

  SafeList = []
  for k in ABC:
    A, B, C = map(int, k.split())
    checkList = [check(A, B, C), check(C, B, A), check(B, C, A)]
    if(checkList == [-1, -1, -1]):
      SafeList.append("invalid")
    elif(False in checkList):
      SafeList.append("unsafe")
    else:
      SafeList.append("safe")
  return '\n'.join(SafeList) # join문 앞으로 잘 쓸 듯 (https://blockdmask.tistory.com/468)

Y, M, D = map(int, input().split())
N = int(input())

for k in range(N):
  ABC = [input()]
  print(solve())