# -*- coding: utf-8 -*-
"""0320(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CpcB87kGyTUNUxLttjtgJv00MI4Q_xbm
"""

# 프로그래머스 덧칠하기
def solution(n, m, section):
  answer = 0 #최소값 = 정답
  paint = 0 # 페인트칠
  for i in section:
    if i >= paint:
      paint = i + m
      answer += 1

  return answer
  
print(solution(5, 4, [1, 3]))

# 프로그래머스 최댓값과 최솟값
def solution(s):
  answer = ''
  cuttingBlank = s.split(' ')
  cuttingBlank = list(map(int, cuttingBlank))
  
  maxValue = 0
  minValue = 0

  i = 1
  
  for i in range(len(cuttingBlank)):

    maxValue = cuttingBlank[0]
    minValue = cuttingBlank[0]

    if(maxValue < cuttingBlank[i]):
      maxValue = cuttingBlank[i]

    if(minValue > cuttingBlank[i]):
      minValue = cuttingBlank[i]

  answer = str(minValue) + " " + str(maxValue)

  return answer

print(solution("-1 -2 -3 -4"))

    #진짜 너무 간단하게 다시 풀어서 황당할 정도도
    #answer = ''
    #cut = list(map(int, s.split(' ')))
    #answer = str(min(cut)) + " " + str(max(cut))

# 프로그래머스 JadenCase
def solution(s):
  answer = ''
  for i in range(len(s)):
    if(((97 <= ord(s[i]) <= 122) or (65 <= ord(s[i]) <= 90)) != True):
      continue
    if(s[i - 1] == ' '):
      if(97 <= ord(s[i]) <= 122):
        toUpper = chr(ord(s[i]) - 32)
        toUpperList = list(s)
        toUpperList[i] = toUpper
        s = ''.join(toUpperList)
      if(s[i] == ' '):
        continue
    else:
      if(97 <= ord(s[0]) <= 122):
        toUpper = chr(ord(s[0]) - 32)
        toUpperList = list(s)
        toUpperList[0] = toUpper
        s = ''.join(toUpperList)
      if(65 <= ord(s[i]) <= 90):
        toLower = chr(ord(s[i]) + 32)
        toLowerList = list(s)
        toLowerList[i] = toLower
        s = ''.join(toLowerList)
  answer = s
  return answer